export const MATERIAL_ICONS = [
  'add',
  'archive',
  'bar_chart',
  'check',
  'check_circle',
  'chevron_left',
  'chevron_right',
  'close',
  'content_copy',
  'delete',
  'dashboard',
  'edit',
  'error',
  'expand_more',
  'favorite',
  'filter_list',
  'folder',
  'info_i',
  'logout',
  'menu',
  'menu_open',
  'more_horiz',
  'more_vert',
  'priority_high',
  'settings',
  'search',
] as const;
