export const MATERIAL_ICONS = [
  'add',
  'archive',
  'check',
  'chevron_left',
  'chevron_right',
  'close',
  'delete',
  'edit',
  'expand_more',
  'favorite',
  'filter_list',
  'info_i',
  'more_vert',
  'priority_high',
  'search',
] as const;
